# Generated by Django 3.0.8 on 2021-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank='True', null=True),
        ),
    ]
