# Generated by Django 3.0.8 on 2021-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
