# Generated by Django 3.0.8 on 2021-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210602_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
