# Generated by Django 3.0.8 on 2021-03-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_orderitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
