# Generated by Django 3.0.8 on 2021-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
