# Generated by Django 3.0.8 on 2021-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
