# Generated by Django 3.0.8 on 2021-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_siteproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproperties',
            name='purpose',
            field=models.CharField(choices=[('Home Carousel', 'Home Carousel'), ('Home Banner A', 'Home Banner A'), ('Home Banner B', 'Home Banner B')], max_length=200),
        ),
    ]
