# Generated by Django 3.0.8 on 2021-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210322_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproperties',
            name='aux_text_field',
            field=models.TextField(blank=True, default='placeholder text', null=True),
        ),
        migrations.AlterField(
            model_name='siteproperties',
            name='body',
            field=models.TextField(blank=True, default='placeholder text', null=True),
        ),
        migrations.AlterField(
            model_name='siteproperties',
            name='title',
            field=models.CharField(blank=True, default='placeholder text', max_length=200, null=True),
        ),
    ]
